### PR TITLE
add context with timeout timeout to github api call issue#38

### PR DESCRIPTION
**Pull request by frankie-mur**
Add a 5-second context with a timeout to GitHub Pull Request API call. #38 

cool project btw, would love to contribute :) 

## Summary by CodeRabbit

- **Refactor**
	- Improved the `GetPullRequest` function with a timeout for better performance and reliability when fetching pull request data.
- **New Features**
	- Added a search functionality to the app.

### CODE REVIEW

**Review by kmesiab — COMMENTED** [review]
Hi there,

First off, I really appreciate your contribution to our project and thanks for submitting this PR!

I've taken a look and everything seems excellent. I do have a small suggestion for improvement. It might be beneficial to make the timeout configurable, possibly through an environment variable, with a fallback to 5 seconds. This could add flexibility to the functionality.

Additionally, if you decide to implement this change, it would be great to define the default value as a constant. This can help in maintaining clarity and consistency in our codebase.

I'd love to hear your thoughts on these suggestions. Thanks again for your valuable input!

Best regards,
Kevin

**Comment by frankie-mur** [comment]
> Hi there,
> 
> First off, I really appreciate your contribution to our project and thanks for submitting this PR!
> 
> I've taken a look and everything seems excellent. I do have a small suggestion for improvement. It might be beneficial to make the timeout configurable, possibly through an environment variable, with a fallback to 5 seconds. This could add flexibility to the functionality.
> 
> Additionally, if you decide to implement this change, it would be great to define the default value as a constant. This can help in maintaining clarity and consistency in our codebase.
> 
> I'd love to hear your thoughts on these suggestions. Thanks again for your valuable input!
> 
> Best regards, Kevin

Hey @kmesiab this is a great suggestion! I will look into implementing this, what do you think is a good default value? I have put 5 seconds at the moment but am open to suggestions, thanks again.

**Comment by kmesiab** [comment]
> I have put 5 seconds at the moment

I think that's fine.

**Review by kmesiab — CHANGES_REQUESTED** [review]
Looks good!  Can you squash these into a single commit?

**Comment by frankie-mur** [comment]
squashed  👍

**Pull request merged**
